### PR TITLE
fix: do not generate sdk everytime

### LINKED ISSUE #70: generated sdk should not be regenerated every npm install
The sdk should not be generated every time we use the command `npm install`, it generates a lot of output and makes harder to know what `npm install` has done.

### PR DESCRIPTION
**Pull request by gboutry**
#### Which issue(s) this PR fixes

Fixes #70

#### Agreements

- [X] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [X] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Comment by PaulFarault** [comment]
We may want to rename `downloadGenerator.sh` to `generator.sh` or sth similar as it's not only downloading now?

File: scripts/downloadGenerator.sh [hunk 1]
```diff
@@ -1,6 +1,16 @@
+#!/bin/bash
+
 OPENAPI_JAR_URL=https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/6.2.0/openapi-generator-cli-6.2.0.jar
+HASH_FILE="build/tdp-server_0.1.0_openapi.json.sha256"
 
 echo "Downloading $OPENAPI_JAR_URL"
 wget --no-clobber $OPENAPI_JAR_URL -O openapi-generator-cli.jar
+if [[ -z "$FORCE_OPENAPI_GEN" && -d "build/tdp-sdk" && $(sha256sum --check "$HASH_FILE") ]]
+then
+    echo "Skipping client generation..."
```
Comment (PaulFarault) [inline scripts/downloadGenerator.sh:10]: We may want to add sth like "No schema change, skipping client generation." to explicitly indicate that client will be regen at each schema change?

**Comment by PaulFarault** [comment]
> We might, but it's not in the scope of the PR. Do you want me to rename it ?

@gboutry yes please, I'm not sure that it's worth it to reopen a PR for that.
